# Generated by Django 3.2.14 on 2022-07-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_person_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Person name')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('username', models.CharField(max_length=60)),
                ('approved', models.CharField(max_length=20, verbose_name='Approved')),
            ],
        ),
        migrations.CreateModel(
            name='class_person_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Person name')),
                ('username', models.CharField(max_length=60)),
                ('imgname', models.CharField(max_length=200)),
                ('approved', models.CharField(max_length=20, verbose_name='Approved')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
