# Generated by Django 3.2.14 on 2022-07-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_db', '0002_auto_20220801_0207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassPersonImages',
            new_name='ClassPersonImage',
        ),
    ]
