# Generated by Django 3.2.14 on 2022-08-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_db', '0004_auto_20220801_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classpersonimage',
            name='imgname',
        ),
        migrations.AddField(
            model_name='classpersonimage',
            name='img',
            field=models.ImageField(default=3, upload_to='class_a/'),
            preserve_default=False,
        ),
    ]
