# Generated by Django 3.2.14 on 2022-08-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_db', '0005_auto_20220801_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classpersonimage',
            old_name='person_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='classpersondescription',
            name='approved',
            field=models.CharField(default='Yes', max_length=20, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='classpersonimage',
            name='approved',
            field=models.CharField(default='Yes', max_length=20, verbose_name='Approved'),
        ),
    ]
