# Generated by Django 3.2.14 on 2022-08-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_db', '0006_auto_20220801_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpersondescription',
            name='ip',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='classpersondescription',
            name='username',
            field=models.CharField(default='admin', max_length=60),
        ),
        migrations.AlterField(
            model_name='classpersonimage',
            name='username',
            field=models.CharField(default='admin', max_length=60),
        ),
    ]
