# Generated by Django 3.2.14 on 2022-08-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_db', '0007_auto_20220801_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpersonimage',
            name='ip',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
