# Generated by Django 3.2.14 on 2022-08-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_db', '0008_classpersonimage_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpersondescription',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classpersonimage',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
