# Generated by Django 3.2.14 on 2022-08-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_db', '0011_auto_20220802_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpersondescription',
            name='approved',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=1, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='classpersonimage',
            name='approved',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='y', max_length=1, verbose_name='Approved'),
        ),
    ]
