# Generated by Django 3.2.14 on 2022-08-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_db', '0013_classbulkupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassBulkUpload',
            new_name='ClassZipUpload',
        ),
    ]
