# Generated by Django 3.2.14 on 2022-08-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn_db', '0014_rename_classbulkupload_classzipupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTrainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=120, verbose_name='Comment')),
                ('username', models.CharField(default='admin', max_length=60)),
                ('status', models.CharField(default='Processing', max_length=60)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
