# Generated by Django 3.2.14 on 2022-08-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassCdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstructureimage',
            name='img',
            field=models.ImageField(upload_to='class_c/'),
        ),
    ]
