# Generated by Django 3.2.14 on 2022-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassCdb', '0003_classtrainmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstructuredescription',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Structure name'),
        ),
    ]
