# Generated by Django 3.2.14 on 2022-08-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_D_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTrainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=120, verbose_name='Comment')),
                ('username', models.CharField(default='admin', max_length=60)),
                ('status', models.CharField(default='Processing', max_length=60)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='classzipupload',
            name='approved',
        ),
        migrations.AlterField(
            model_name='classtoolimage',
            name='img',
            field=models.ImageField(upload_to='class_d/'),
        ),
    ]
