# Generated by Django 3.2.14 on 2022-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Class_D_db', '0002_auto_20220806_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtooldescription',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Tool name'),
        ),
    ]
